# Generated by Django 3.2.4 on 2021-06-24 04:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210624_0403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'portfolio_detail', 'verbose_name_plural': 'portfolio_details'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default=datetime.datetime(2021, 6, 24, 4, 33, 36, 740761, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
