# Generated by Django 3.2.4 on 2021-06-26 03:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210624_0433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={},
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='link',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='created',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='details',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='title',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='updated',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='contenido',
            field=models.TextField(default=datetime.datetime(2021, 6, 26, 3, 45, 7, 648025, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(),
        ),
    ]
