# Generated by Django 3.2.4 on 2021-06-26 03:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20210626_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='titulo',
            field=models.CharField(default=datetime.datetime(2021, 6, 26, 3, 49, 37, 169751, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.URLField(blank=True, null=True),
        ),
    ]
