# Generated by Django 3.2.4 on 2021-06-29 05:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_rename_contenido_portfolio_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'portfolio', 'verbose_name_plural': 'portfolios'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='id_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio.category'),
            preserve_default=False,
        ),
    ]
