# Generated by Django 3.2.4 on 2021-06-29 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20210629_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='id_details',
        ),
    ]
