# Generated by Django 3.2.4 on 2021-07-07 01:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_remove_portfolio_id_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='greetings_3',
            field=models.CharField(default=datetime.datetime(2021, 7, 7, 1, 41, 47, 231205, tzinfo=utc), max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings_2',
            field=models.CharField(max_length=6),
        ),
    ]
